language: node_js

node_js:
  - 'node'
  - '10'
  - '8'

install: npm install

script:
  - npm run lint
  - npm run test:coveralls
  - npm run license
  - npm run build

cache:
  directories:
    - node_modules

notifications:
  email:
    on_success: never
    on_failure: always
