language: node_js

node_js:
  - 'node'
  - '10'
  - '8'

install: npm install

script:
  - npm run build && npm run license

cache:
  directories:
    - node_modules

notifications:
  email:
    on_success: never
    on_failure: always
